name: repository structure
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "../.."
          type: ".html"

      - name: Output results
        id: list
        run: |
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done

      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with: 
          path: stylesList.txt
          contents: ${{ steps.list.outputs }}
          write-mode: overwrite

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          # message: 'Overwritten by Github Actions - ${date}'

        


