name: repository structure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filelist.outputs.file_names }}
    steps:
      - uses: actions/checkout@v2
      - name: Get all html files
        id: filelist
        uses: the-coding-turtle/ga-file-list@v0.2
        with:
          file_extension: "html"