name: repository structure
on: [push]
jobs:

  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x, 15.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build --if-present
        - run: npm test

  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v2

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: ".."
          type: ".html"

      - name: Output results
        run: |
          for i in ${{steps.pl.outputs.paths}}; do
          echo $i
          done


      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with: 
          path: stylesList.txt
          contents: ${{steps.pl.outputs.paths }}
          write-mode: overwrite

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          # message: 'Overwritten by Github Actions - ${date}'

        


