name: repository structure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write a multi-line message
        run: |
          echo This demo file shows a very basic and easy-to-understand workflow.